name = "Lucas' War Factions SMP Pack"
author = "Lucas"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce9d07c6f212b4f2a2e6753e5dee7c0d4cd742b431c0203f35f52e562f531790"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
